name: 'build with docker'

on:
  push:
    tags:
      - "v*"
  pull_request:
    types:
      - closed
    branches:    
      - 'qa'

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      #lowecase of repository name
      - id: string
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{github.event.repository.name}}
      # prepear metadata
      - name: construct release tagging
        run: |
          IMAGE_TAG="massoft/${{steps.string.outputs.lowercase}}:${{github.ref_name}}"
          IMAGE_TAG_LATEST="massoft/${{steps.string.outputs.lowercase}}:latest"
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          echo "IMAGE_TAG_LATEST=${IMAGE_TAG_LATEST}" >> $GITHUB_ENV
          echo "building ${IMAGE_TAG_LATEST}"
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v2
      - name: build docker tag image
        run: |
          docker build --build-arg "TOKEN=${{ secrets.GIT_ACCESS_TOKEN }}" . -t "${IMAGE_TAG}"
          docker push "${IMAGE_TAG}"
      - name: build docker latest image
        run: |
          docker build --build-arg "TOKEN=${{ secrets.GIT_ACCESS_TOKEN }}" . -t "${IMAGE_TAG_LATEST}"
          docker push "${IMAGE_TAG_LATEST}"